### ISSUE TITLE
sanity check for rcutils_steady_time_now

### ISSUE THREAD

**Issue by serge-nikulin** [ros2/rcutils#88] opened 2018-02-05 20:48 UTC
`rcutils_steady_time_now` currently trusts the OS specific implementations to provide truly monotonic time values. Issue #86 and [Internet](https://stackoverflow.com/questions/3657289/linux-clock-gettimeclock-monotonic-strange-non-monotonic-behavior) show the monotonicity claim should be verified.

**Comment by mikaelarguedas** [comment] 2018-02-07 17:51
Thanks @serge-nikulin, we were indeed using "true" monotonic clocks in the past and changes the behavior to match what we get from chrono at the c++ level. linking to the relevant issue here for book-keeping: https://github.com/ros2/rcutils/issues/43

**Comment by serge-nikulin** [comment] 2018-02-07 18:03
@mikaelarguedas, because of non-monotonic Windows steady timer (due to overflow in previous ROS2 implementation, fixed by https://github.com/ros2/rcutils/pull/87) I had a silent failure in a publisher's executor.

This fix forces the system to non-silent error state in similar failure mode on all platforms.

**Comment by clalancette** [comment] 2022-04-22 21:21
I'm going to close this as sort of a duplicate of #43.  If you disagree, feel free to reopen (but I think we need an explicit actionable thing to do here).

**Closed by clalancette** 2022-04-22 21:21 UTC
Labels: in progress
