### ISSUE TITLE
logging_macros.h not found

### ISSUE THREAD

**Issue by PandaSel** [ros2/rcutils#356] opened 2022-04-18 09:03 UTC
Hi,

I am compiling ros2 and some libraries refer to logging_macros.h(rcutils/logging_macros.h), but there is no such file in rcutils.

branch: foxy

Follow the ros2 configuration：https://docs.ros.org/en/foxy/Installation/Ubuntu-Development-Setup.html, when executing 'colcon build --symlink-install', Below is the error info:

--- stderr: rcutils                                                                                                                                                               
/bin/sh: 1: c: not found
/home/dschen/ros2_foxy/src/ros2/rcutils/src/split.c:26:10: fatal error: rcutils/logging_macros.h: No such file or directory
   26 | #include "rcutils/logging_macros.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rcutils.dir/build.make:290: CMakeFiles/rcutils.dir/src/split.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Please tell me how to solve this issue!

Thanks a lot!

**Comment by clalancette** [comment] 2022-04-18 13:01
I'm not sure what the issue is, but it seems like you have a misconfiguration somewhere; you shouldn't be seeing:

```
/bin/sh: 1: c: not found
```

That said, please open questions like this on https://answers.ros.org, which is our central question and answer site.  I'll close this for now.

**Closed by clalancette** 2022-04-18 13:01 UTC
