### ISSUE TITLE
CMakeFiles.txt lib dir  is fixed

### ISSUE THREAD

**Issue by jiangqii** [ros2/rcutils#459] opened 2024-04-08 03:51 UTC
```
install(TARGETS ${PROJECT_NAME} EXPORT ${PROJECT_NAME}
  ARCHIVE DESTINATION lib
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin)
```
This is not a dynamic change, it is recommended to use variables from cmake
```
install(TARGETS ${PROJECT_NAME} EXPORT ${PROJECT_NAME}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
```

**Comment by clalancette** [comment] 2024-04-08 11:44
> This is not a dynamic change, it is recommended to use variables from cmake

From what I understand, we can only do this if we use `GNUInstallDirs`, which we don't currently do.  We've had some discussions about switching to this (see https://github.com/ros2/ros2/issues/1465), but we haven't gotten there yet.

I'm going to close this as a duplicate of https://github.com/ros2/ros2/issues/1465

**Closed by clalancette** 2024-04-08 11:44 UTC
